Add endpoints to insert and query store information from Spanner database
googleinterns/smb-fos-tracker pull request #10
Opened 2020-06-08 19:55 UTC by vanshikagoogle

Added java servlet AddStoreServlet to accept store in request body and then upload that to spanner.
Added java servlet GetStoresServlet to query store phone#, email and coordinates from spanner.
Updated Store.java to return owner's name

2020-06-15 09:57 UTC, trblessy requested changes

2020-06-15 09:57 UTC, trblessy commented on FosServer/src/main/java/com/example/fostracker/servlets/AddStoreServlet.java
> +@WebServlet(value = "/stores/add")
please add comments for public classes.

2020-06-15 09:57 UTC, trblessy commented on FosServer/src/main/java/com/example/fostracker/servlets/HelloAppEngine.java
> +/*
Do we need this servlet?

2020-06-16 08:15 UTC, krati-tiwari approved these changes

2020-06-16 08:50 UTC, vanshikagoogle commented on FosServer/src/main/java/com/example/fostracker/servlets/HelloAppEngine.java
> +/*
I can remove it

2020-06-16 08:52 UTC, trblessy approved these changes

2020-06-16 08:53 UTC, merged